version: '3.7'

services:
  db_posgtgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: system

  consul:
    image: consul:1.7.1
    ports:
      - 8500:8500

